### ISSUE TITLE
\begin snippets 

### ISSUE THREAD

**Issue by KerouichaReda** [area/language-latex#102]
when we use \begin snippets we obtain an another \ in the begin

**Comment by yudai-nkt** [comment]
As [the snippet definition](https://github.com/area/language-latex/blob/bf2ee136a35b76a6476d984830729d1654c2a326/snippets/language-latex.cson#L34-L36) suggests, you just have to type `begin` without a leading backslash. If you are already doing so, please let me know with concrete information (i.e., reproducible code sample and what kind and version of OS/Atom/package you are using).

![snippets](https://cloud.githubusercontent.com/assets/13291527/20203585/ed0a4ea0-a80b-11e6-88a5-3b5731c43654.gif)

**Comment by Aerijo** [comment]
@yudai-nkt can this be closed please? The issue was intended behaviour and it's obvious the asker was starting his snippet with a backslash.

Whether this should be the default behaviour is another issue.
