### ISSUE TITLE
Syntax highlighting bug with closing tags

### ISSUE THREAD

**Issue by acenicks** [area/language-latex#103]
I am having a bug which seems to be specific to the line I am editing.
![atom_bug_it](https://cloud.githubusercontent.com/assets/1060006/20334934/1cc6e0c6-ab8c-11e6-99d1-3a76c1cbd8c0.png)
the above screenshot shows how the italic text is going beyond the closing curly brackets. But if I remove the italics, the bug gets propagated to the next element:
![atom_bug_eqn](https://cloud.githubusercontent.com/assets/1060006/20334973/71679738-ab8c-11e6-917d-938029ace9ba.png)
and only ends when the paragraph ends. The rest of the paragraphs are unaffected by this. If I simply enclose any text with curly brackets, complete stylization of the paragraph disappears: 
![atom_bug_cb](https://cloud.githubusercontent.com/assets/1060006/20335012/c251dd20-ab8c-11e6-9aea-dd3b97786b9f.png)

**Comment by area** [comment]
This looks like the per-line token limit in atom rearing its head again: https://github.com/atom/atom/issues/1667

**Comment by acenicks** [comment]
Thank you. I guess its best to follow progress on this issue over at [atom/atom#1667](https://github.com/atom/atom/issues/1667).
