### ISSUE TITLE
Enable highlighting for knitr-enabled Latex files

### ISSUE THREAD

**Issue by dennisguse** [area/language-latex#105]
knitr is a preprocessor for executing R scripts (computations, plotting) before compiling the actual Latex code [1].
Before compiling to .tex knitr files have the ending .Rnw (at least to my knowledge) [2].

Thus, syntax highlighting is not enabled for those files...

[1] http://yihui.name/knitr/
[2] http://kbroman.org/knitr_knutshell/pages/latex.html

**Comment by mathuin** [comment]
When I open `.Rnw` files, I can set the file type to `LaTeX`, and the `language-latex` package highlights the syntax pretty much as I expect.

It does not treat the actual R code properly, though, especially `$` and `%`.  Here is a small example:

````
\begin{document}
    <<example, echo=FALSE>>=
    targets <- c(23.9, 23.9, 23.9, 18.3, 12.8, 12.8, 12.8, 18.3, 18.3)
    initial.raw <- read.csv("Fermentation Log - Initial.csv", header=TRUE, stringsAsFactors=FALSE)
    initial.tidier <- initial.raw %>% separate(Replicant, into = c("Tank", "Treatment"), 1)
    initial.tidy <- initial.tidier %>% mutate(Time = as.POSIXct(Time))
    initial.tidy$Target = targets[as.numeric(initial.tidy$Tank)]
    @
\end{document}
````

The code between `<<...>>=` and `@` is R code, and should not be highlighted as if it were LaTeX.  The `$`'s are being misunderstood as math-mode delimiters by the highlighter, and the `%`'s as comments.

I do not know if Atom is clever enough to allow for multiple language plugins to handle the same file simultaneously.  That would be totally rad, but amazingly hard to implement I suspect.

That being said, it would probably be sufficient for `language-latex` to treat stuff between `<<...>>=` and `@` as if it were inside a verbatim environment or something, completely unremarkable.
