### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by MrYann** [area/language-latex#107]
My understanding is that this package is used by the built-in spell-check package, which is great.

However, many latex commands (not all, but most of them) are underlined as spelling errors. Could this be fixed ?

**Comment by PierreMarchand20** [comment]
I am waiting for this to be included in atom to solve the problem you mentioned : atom/spell-check#157

**Comment by Aerijo** [comment]
This package is not supported by the built in spell-check package.

See https://github.com/area/language-latex/issues/124.

**Comment by Aerijo** [comment]
@MrYann I've added more detailed information to the other issue, please close this one. If you need more assistance, ask for it over there.
