### ISSUE TITLE
Highlight error

### ISSUE THREAD

**Issue by giovannibenussi** [area/language-latex#108]
When I wrote the following code the _\textit{}_ tag isn't highlighted:

`Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \ref{fig:example}, Lorem ipsum dolor sit amet \textit{a}, \textit{b}, \textit{c}, \textit{d}, \textit{e}, \textit{f}, \textit{g}, \textit{h}, \textit{i}, \textit{j}, \textit{k} asd asd asd \textit{ab}, \textit{bc}, \textit{cd}, \textit{de}, \textit{ef}, \textit{fg}, \textit{gh}, \textit{hi}, \textit{ij}, \textit{jk}.`

The output is the following:

![image](https://cloud.githubusercontent.com/assets/1259399/20561908/af1eb704-b15f-11e6-88fb-696fe9584ef5.png)

Also, if I write the following code:

`Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua \textit{a}, \textit{b}, \textit{c}, \textit{d}, \textit{e}, \textit{f}, \textit{g}, \textit{h}, \textit{i}, \textit{j}, \textit{k} asd asd asd \textit{ab}, \textit{bc}, \textit{cd}, \textit{de}, \textit{ef}, \textit{fg}, \textit{gh}, \textit{hi}, \textit{ij}, \textit{jk}.`

I get this output:

![image](https://cloud.githubusercontent.com/assets/1259399/20561928/c78722f4-b15f-11e6-82b4-79d9a2bc2017.png)

**Comment by Aerijo** [comment]
Related to grammar token limit. Only workaround I know is to load package https://atom.io/packages/grammar-token-limit and set to a higher limit. This may slow Atom down.
