### ISSUE TITLE
User added snippets?

### ISSUE THREAD

**Issue by mkoske** [area/language-latex#114]
Hello,

how the snippet system works? Would it be easy to add an ability for user to add own snippets?

It's probably not best way always to edit this extensions file to add something, right?

Regards,
Miika

**Comment by dmorgorg** [comment]
In Atom, File>Snippets... and add your own. I'm not sure but editing the extension might get overwritten on update.

**Comment by Aerijo** [comment]
See the flight manual http://flight-manual.atom.io/using-atom/sections/snippets/. Note that for ~~stupid~~ technical reasons, it is very difficult to get snippets working in math mode or quotes (anything considered a string).

**Comment by yudai-nkt** [comment]
This seems to be a general Atom question. [This](http://flight-manual.atom.io/using-atom/sections/snippets/#creating-your-own-snippets) will help.
