### ISSUE TITLE
Quotes Bug

### ISSUE THREAD

**Issue by caspar** [area/language-latex#115]
<img width="316" alt="screen shot 2016-12-14 at 15 34 41" src="https://cloud.githubusercontent.com/assets/5422063/21185930/e6384ae8-c212-11e6-84d6-e80a2ece5a7e.png">

**Comment by XachaB** [comment]
I still have this issue, how to resolve it ?

**Comment by sierxue** [comment]
I still have this issue, how to resolve it ?
