### ISSUE TITLE
Double backticks causes highlighting error.

### ISSUE THREAD

**Issue by gnat79** [area/language-latex#118]
Double backticks seem to cause a highlighting error. Notice that the text is green after using the double backticks, and it does not change back when the `"` is used on the other end.

![screen shot 2017-01-14 at 4 03 24 pm](https://cloud.githubusercontent.com/assets/11506551/21958086/02fba5b2-da73-11e6-95ea-02a97cc70621.png)

**Comment by Aerijo** [comment]
LaTeX does not normally end quotes with " (double stright quote). Use '' instead (two single straight quotes). The regular expression for the end of this string environment reflects this. 

If you desperately need this (which is unlikely), go into the latex grammar file (.atom -> packages -> language-latex -> grammars -> latex.cson), do a search for `` (double backtick; should be line 1890) and replace the entry to 'end' with '\'\'|"' (as below). This will make it stop at two single straight quotes OR a double straightquote.

`    'end': '\'\'|"'
`

**Comment by Aerijo** [comment]
If this fixes your problem, please close the issue. I doubt there will be any support for a `"` to close a quote, and hopefully scoping quotes will be removed entirely anyway eventually.

If you really need this, please implement the solution and then close. I can provide more help on how to add it if you need.

**Comment by gnat79** [comment]
Yes, this is actually operator error :-) I'll happily close it. Thank.
