### ISSUE TITLE
Only highlights a certain number of commands in one code line.

### ISSUE THREAD

**Issue by Stan125** [area/language-latex#123]
<img width="952" alt="bildschirmfoto 2017-03-21 um 12 25 52" src="https://cloud.githubusercontent.com/assets/17404160/24145480/8fa91750-0e31-11e7-96fc-17f2a51eae24.png">

Note that after 9 highlights the highlighting stopped.

**Comment by Swoy** [comment]
This is an issue for me as. It seems to be a limitation of \n$0? Is this something related to Atom?

**Comment by tompo-andri** [comment]
Maybe it has something to do with multiple use of the same latex keyword, here you have `\emph` but I have exactly the same problem with multiple `\cite` in one single line. Just for information, on my side it breaks around the 600 character into the third or fourth `\cite` but I see no pattern.

**Comment by Swoy** [comment]
No, there is a very concrete pattern, after exactly 1000 characters in one line it happens, no matter what is used before. As shown in the image below, only `\c` is highlighted, as they are characters 999 and 1000.

<img width="964" alt="issue" src="https://cloud.githubusercontent.com/assets/5272077/25224976/46bb930a-25c0-11e7-8201-cc2b09e017eb.png">

This makes me believe that the issue relates to the token limit in Atom, which is discussed in [Atom/#1667](https://github.com/atom/atom/issues/1667)
As it stands, this will not be solved until they've looked at possible ways to release token limitations without crashing the application.

Someone made a package that admittedly should work around this limit. You can read more about that [here](https://atom.io/packages/grammar-token-limit) (did not work for me)

**Comment by Aerijo** [comment]
Solution is for package author to add "limitLineLength: no" to the top of the grammar file.

**Comment by Aerijo** [comment]
By the way, there are two issues here: it will stop looking for matches after ~1000 characters, and it will also stop looking after ~147 matches. My solution (pull requested) solves the first problem, not the latter (though you might want to consider not having this many commands on one line anyway).

**Comment by yudai-nkt** [comment]
This should be closed by the PR above.
