### ISSUE TITLE
Multiple mixed subscript/superscript math mode sections in a paragraph causes permanent math mode

### ISSUE THREAD

**Issue by pdaniell** [area/language-latex#125]
The following screenshot shows the error. If you use math mode several times in a paragraph with mixed superscript and subscripts, after seven times, the highlighter gets "stuck" on math mode (orange below) instead of returning the context back to regular text.

![screenshot from 2017-04-08 23-53-55](https://cloud.githubusercontent.com/assets/5911713/24833086/aa2362c8-1cb6-11e7-8c62-48b5d9c60ff4.png)

**Comment by Aerijo** [comment]
Atom has a token limit that only allows a certain number of grammar matches per line. A cleaner way to see this is to copy and paste \a\a\a\a\a until it no longer turns blue. This limit can be extended by using the grammar-token-limit package, but can potentially slow the editor down.

Alternatively, as your example shows, a line break resets this limit and everything works again. LaTeX does not do anything at a line break (only blank lines split paragraphs), so try to put sentences on new lines if this is still an issue.

**Comment by pdaniell** [comment]
Thanks I consider this fixed, so I will close the issue.
