### ISSUE TITLE
Highlighting after character 1000

### ISSUE THREAD

**Issue by frotched** [area/language-latex#127]
Any commands after the 1000th character in a line are not caught as syntax. For example, if \cite{Citation2017} began on character 996, only the first 5 characters would be highlighted. 

Could it be changed to 2000?

**Comment by apalkowski** [comment]
I think that's not the package's fault, rather it's Atom's token limit. You can rise the limit by installing https://atom.io/packages/grammar-token-limit and setting an appropriate value in its options.

**Comment by Swoy** [comment]
Also, instead of reporting new issues, you could search the issues already here.  Have a look at #123  :)

**Comment by Aerijo** [comment]
@frotched @apalkowski Please close this issue, I explain it better in #123. TL;DR: Limit can be removed entirely.

**Comment by yudai-nkt** [comment]
This should be closed by the PR above.
