### ISSUE TITLE
Markup not working correctly

### ISSUE THREAD

**Issue by romanovzky** [area/language-latex#13]
The markup highlight seems to break if the equation environment has a pmatrix environment nested in it (see screenshots).

![1](https://cloud.githubusercontent.com/assets/7794475/3174216/6f851e04-ebef-11e3-84cc-c49a00b47631.png)
![2](https://cloud.githubusercontent.com/assets/7794475/3174217/6f853416-ebef-11e3-8840-8cb9acdcaf25.png)

**Comment by Rabib** [comment]
@romanovzky you may have a solution here: https://atom.io/packages/grammar-token-limit

**Comment by cedhuf** [comment]
As on https://github.com/area/language-latex/issues/11 :
>Don't seems to be a [Language-latex](https://github.com/area/language-latex) issue, but more a current atom ~~bug~~ **feature**. When line is too long, colorization breaks at a certain limit, currently ~~seems~~ **set** to ~~be~~ 100. Please, follow https://github.com/atom/atom/issues/1667 for more updates on this.

As @Rabib sugested, you can change this behavior using [grammar-token-limit](https://atom.io/packages/grammar-token-limit) package.

**Comment by fhenneke** [comment]
is the token limit related to the problem mentioned by @romanovzky, where
```
\newcommand{\beq}{\begin{equation}}
\newcommand{\eeq}{\end{equation}}
```
messes up the markup? or should a seperate issue be opened?

**Comment by cedhuf** [comment]
Probably not. It should be a new issue.
