### ISSUE TITLE
expl3 syntax regressions

### ISSUE THREAD

**Issue by Evpok** [area/language-latex#150]
I did not notice before because I hadn't used LaTeX3 syntax for a while, but it seems that there are some regressions. Most notably

  - The latex3-style parameter sigils (`:N` and consorts) are not highlighted as advertised in https://github.com/area/language-latex/issues/48#issuecomment-242787288
  - Highlighting switches back to LaTeX2e within braces
  - Leading double underscores in commands are not supported
  - Commands with a single underscore in their names are not supported

```latex
\ExplSyntaxOn
    \tl_new:N\single_underscore
    \tl_new:N\__two_leading_underscores
    \tl_set:Nn\g_correctly_highlighted{\but_this_isnot}
    \tl_new:N\g_file_seq_name_tl
    \tl_gset:Nn\g_file_seq_name_tl{g_file_name_seq}
    \seq_gpush:cV{\tl_use:N\g_file_seq_name_tl}\l_tmpa_tl
\ExplSyntaxOff
```

![screenshot_20170923_190020](https://user-images.githubusercontent.com/1656541/30775327-75141b9a-a091-11e7-9a82-9af2e58d6cfb.png)

Version infos:

  - `language-latex`: 1.1.1

```bash
$ atom-beta --version
Atom    : 1.21.0-beta1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by yudai-nkt** [comment]
Sorry for the slow response.

> The latex3-style parameter sigils (`:N` and consorts) are not highlighted as advertised in #48 (comment)

It seems that argument specifications are correctly highlighted in your screenshot as well.

> Highlighting switches back to LaTeX2e within braces

Yes, I know this problem although I haven't made a corresponding issue here. Please refer to yudai-nkt/language-tex#9.

> Leading double underscores in commands are not supported

Leading double underscores mean that the command is a private expl3 function and therefore requires a following argument specification. So, `\__two_leading_underscores` is not highlighted on purpose while something like `\__two_leading_underscores:Npm` is highlighted.

> Commands with a single underscore in their names are not supported

Commands with a single underscore mean that the command is an expl3 function and therefore requires a following argument specification.

All of the expl3 support is based on the naming convention documented in the section 3.2 of [`expl3.pdf`][expl3-doc]. Please let me know if I have some misunderstandings about expl3.

[expl3-doc]: http://mirrors.ctan.org/macros/latex/contrib/l3kernel/expl3.pdf

**Comment by Evpok** [comment]
>> The latex3-style parameter sigils (:N and consorts) are not highlighted as advertised in #48 (comment)
>
> It seems that argument specifications are correctly highlighted in your screenshot as well.

They are of the same colour as the command name, whereas in https://github.com/area/language-latex/issues/48#issuecomment-242787288 they are of a different one.

![image](https://user-images.githubusercontent.com/1656541/31811704-cf05fd04-b580-11e7-8dae-b8d3edb03b34.png)


> Leading double underscores mean that the command is a private expl3 function and therefore requires a following argument specification. So, \__two_leading_underscores is not highlighted on purpose while something like \__two_leading_underscores:Npm is highlighted.

I can live with that, I just noticed it while checking for other regressions, my initial issue being with commands with a single underscore.

> Commands with a single underscore mean that the command is an expl3 function and therefore requires a following argument specification.

Commands (well, macros) with a single underscore are used for variable names, as in e.g. `\g_ior_file_name_seq` (from espl3 doc), or indeed `\g_file_seq_name_tl`…

**Comment by yudai-nkt** [comment]
> They are of the same colour as the command name, whereas in #48 (comment) they are of a different one.

I think that is more of a problem of syntax theme you're using. What's scope for the argument specification? It should be `support.function.type.expl3.latex`.

> Commands (well, macros) with a single underscore are used for variable names

I misunderstood you meant macros containing only one underscores by "single". `\g_file_seq_name_tl` is a valid expl3 variable and should be highlighted. [The current regex](https://github.com/area/language-latex/blob/044561e6d724f7c9c5254f891fce9fc412b5203d/grammars/latex.cson#L120-L123) seems to [correctly parse](https://regex101.com/r/N0nTrr/1) the expl3 variables, but I'll investigate what breaks the functionality.

**Comment by Evpok** [comment]
> I think that is more of a problem of syntax theme you're using. What's scope for the argument specification? It should be support.function.type.expl3.latex.

Indeed it is, sorry for that, I tend to forget that base16 themes tend to be light on distinctions like this one.

> I misunderstood you meant macros containing only one underscores by "single". \g_file_seq_name_tl is a valid expl3 variable and should be highlighted. The current regex seems to correctly parse the expl3 variables, but I'll investigate what breaks the functionality.

Actually, reading back my original message, that's what it meant and `\single_underscore` is indeed not a name that should be used according to expl3's guidelines. Still feels a bit odd that the syntax highlighter should enforce it this strictly, but OK.

Sorry for bothering you, I should have looked at my original example before answering. (I do have other issues with expl3 syntax in a cls file, but that's another issue)
