### ISSUE TITLE
Syntax highlighting broken with minted environment.

### ISSUE THREAD

**Issue by GoPavel** [area/language-latex#152]
I'm find bug of highlighting c++ code with brackets. All statements in brackets have one color.
1) with brackets
![default](https://user-images.githubusercontent.com/28822150/31322204-44c0da66-ac9c-11e7-9e09-116d2820e579.png)

2) without brackets
![default](https://user-images.githubusercontent.com/28822150/31322209-6badffa0-ac9c-11e7-9023-a1c579fd717f.png)

**Comment by Aerijo** [comment]
This is not a problem with this package, it is to do with how C is highlighted. Normal highlighting works fine (like your second example), it just uses a list of rules to follow. When it reaches the command `\end{minted}`, it reverts back to Latex.

However, when using something like the braces, it does some bracket-specific stuff and then refers back to these "base" highlighting rules ([seen here](https://github.com/atom/language-c/blob/6038fa39738f6f9fe9bbf4988271c464edf75e97/grammars/c.cson#L395-L397)). This is all well and good for pure C/C++, but when embedded like yours the base language is not C &mdash; it's Latex.

This can actually be seen by trying Latex syntax inside, which will highlight correctly.

Therefore, I'll close this issue and suggest looking elsewhere for more help. 
For example:
 - https://github.com/atom/language-c/issues/146
 - https://github.com/atom/language-gfm/issues/206
 - https://github.com/atom/language-c/issues/250
