### ISSUE TITLE
wrong highlighting

### ISSUE THREAD

**Issue by pkjkrai66** [area/language-latex#161]
I am attaching a screenshot of paragraph which is wrongly highlighted by Atom. I am comparing it with highlighting of Notepad++. I have packages [LaTeX](https://atom.io/packages/latex) and [language-latex](https://atom.io/packages/language-latex) in my Atom.
![atomnpp comparision](https://user-images.githubusercontent.com/19630517/33756107-e608ceae-dc19-11e7-955f-b533fd4f406f.PNG)

PS:  I have many markdown supporting packages installed in my Atom.
Text:
```
\chapter{Mathematical Formulation}

For the formulation of GP, the conditional property of Gaussian distribution is used, that is, if two sets of random variable are jointly Gaussian, then the distribution of one set conditioned on the other set is also Gaussian. Let the training dataset is given by,$ \mathcal{D} = \left\{ {\left( {{{\bf{x}}_i},{{\tilde y}_i}} \right)|i = 1, \ldots ,N;{{\bf{x}}_i} \in {\mathbb{R}^m};{{\tilde y}_i} \in \mathbb{R}} \right\}, $ where, \( {{\bf{x}}_i}\) is input vector, \(m\) is the number of independent variables, ${\tilde y_i}$ is the corresponding observation and \(N\) is the number of observations. All training input vectors are arranged in \(N \times M\) design matrix (\({\bf{X}}\)) and the observations are collectively represented by vector ${\bf{\tilde y}}$. The observations have independent and identically distributed noise, which are normally distributed with mean zero and standard deviation $\sigma _y^{} $
```

**Comment by Aerijo** [comment]
I don't get that bug when I use the following text:
```latex
text \( {{\bf{x}}_i}\) text
```

<img width="222" alt="screen shot 2017-12-08 at 5 53 34 pm" src="https://user-images.githubusercontent.com/22167388/33756354-da0acaae-dc40-11e7-99c4-b130d5b2bbce.png">

This seems like where it's going wrong in yours. I may be able to help better if I have something I can copy and paste.

**Comment by pkjkrai66** [comment]
@Aerijo I have updated my post with the test. Not always the highlighting is incorrect. A few paragraphs have been highlighted correctly. I would like to update the fact that, I have many markdown supporting packages installed in my Atom.

**Comment by Aerijo** [comment]
@pkjkrai66 Please wrap your text in ``` (one set on the line above, one below) marks to ensure the backslashes don't get removed (see `\(`)

The result (in the preview) should look like
```
This is literal text, so \( will not be removed
```

**Comment by Aerijo** [comment]
@pkjkrai66 Actually, this ~~might be~~ **is** an old problem I've only just remembered. Try installing the package [`grammar-token-limit`](https://atom.io/packages/grammar-token-limit) and rasing the limit to something higher (I use 300). Details aside, we can;t really fix that issue in this package.

**Comment by pkjkrai66** [comment]
@Aerijo Thanks, it worked.
