### ISSUE TITLE
comment environment is not grayed out

### ISSUE THREAD

**Issue by nemuo** [area/language-latex#165]
### Prerequisites
- [X ] Put an `X` in this box if you have done the following:
  - Ensured the issue has not already been raised
  - Ensured the issue is caused by this package
  - Run `atom --safe`, activated this package, and the issue persisted

### Steps to reproduce & Minimum working example
1.compile tex that includes following

```
\begin{comment}
abc
\end{comment}
```

#### Expected behaviour

abc is grayed out

#### Actual behaviour

color does not change

**Comment by Aerijo** [comment]
Awaiting merge of PR #166

**Comment by Aerijo** [comment]
Merged #166. Now just wait until next release (or use github version of package).
