### ISSUE TITLE
curly braces slow down typing in math mode

### ISSUE THREAD

**Issue by yuehaob** [area/language-latex#176]
Every time I input a pair of curly braces in the equation mode, it becomes unbearably slow to type any words in between them. No issues with square or round brackets. No issue if I disable the language-latex package. No issue if I disable the bracket-matcher package. Does anyone know why this could be the case? Thanks!

**Comment by yudai-nkt** [comment]
While I'd like you to show us a code snippet that reproduces your problem, is this a duplicate of atom/bracket-matcher#341?

**Comment by yuehaob** [comment]
Actually yes! It should be solved now. Thanks!
