### ISSUE TITLE
Commented out text same colour as the rest of the text

### ISSUE THREAD

**Issue by mariaelfving** [area/language-latex#177]
### Prerequisites
- [X ] Put an `X` in this box if you have done the following:
  - Ensured the issue has not already been raised
  - Ensured the issue is caused by this package
  - Run `atom --safe`, activated this package, and the issue persisted

### Description
When commenting out text in a LaTeX document using "%" the text is still the same colour as the rest of the text

### Steps to reproduce & Minimum working example
Change colour of text commented out

#### Expected behaviour
Commented out text to have a different colour

#### Actual behaviour
Commented out text is the same colour

**Comment by Aerijo** [comment]
This sounds like an issue with your theme. Try with `atom-one-dark-syntax`. If it persists, we will need a minimum example we can copy and paste to reproduce the issue with.

**Comment by Aerijo** [comment]
Please reopen if you still have trouble after using the suggested theme. If the other theme works, then it is a problem with the theme you are currently using.
