### ISSUE TITLE
Default soft-wrap

### ISSUE THREAD

**Issue by aengelke** [area/language-latex#18]
See [this commit](https://github.com/atom/language-gfm/commit/32b233ad0d1ae66c0dc4f20ff1bab0b8e0f9df0c).

**Comment by cedhuf** [comment]
Hello,
I do understand that some language like Latex is more usable with soft warp activated. Still soft wrap is an Atom option, in general setting you can activate soft wrap for every file opened with Atom. In language-latex settings you can also activate soft wrap for a given sub language only. I'm not sure it is a good idea to force soft warp for Latex file and not let user choose by themselves what they prefer (globally and language specific).

If there are some others arguments and votes in favor of default soft-wrap activation feel free to let us know.
Br,

**Comment by TimotheeGreg** [comment]
I am for default soft-wrap activation in tex files !

**Comment by Aerijo** [comment]
If it's a default, doesn't that mean the user can change it if they want to? I think it's better for the package to behave optimally "out of the box", without relying on user actions.

**Comment by Aerijo** [comment]
After experimenting, it seems the language settings are entirely configurable; the package settings interface just edits the config file. It is entirely safe to set softwrap as default, and allow user to manually disable if desired. In all likelihood, they won't.  (This will all be latex specific; no affect on other work the user does in Atom)

As I said before, I support optimal setup with minimal configuration. I'll submit a pull request tomorrow.

**Comment by Aerijo** [comment]
Before I do though, @yudai-nkt --- what's your opinion on this?

Pros: 
- Desired behaviour with no setup (who can write/read/edit paragraphs without softwrap?)
- Does not affect any current users who have global softwrap, and any who have given an explicit preference in the config file. Only affects those who have no softwrap globally AND edit latex without softwrap (see above point)
- Easy to (permanently) override in the package settings or (more directly) in the config file
- One less thing for beginners to worry about
- Already implemented in `language-gfm`, the core Atom package for markdown.

Cons: 
- Could confuse someone who deletes the entry in the config file and expects global softwrapping to work.

**Comment by yudai-nkt** [comment]
I myself set to soft wrap, and didn't know that it was default. Go ahead! :rocket:
