### ISSUE TITLE
Support snippets when backslash for commands is already there

### ISSUE THREAD

**Issue by ericcornelissen** [area/language-latex#180]
### Description
Add snippets that work when the command entered already starts with a `\`. If this sounds good I'd love to create a PR for it 😃 

### Current behaviour
![current](https://user-images.githubusercontent.com/3742559/38644690-ace1249e-3de1-11e8-858e-45fa828826ea.gif)

### Expected behaviour
![expected](https://user-images.githubusercontent.com/3742559/38644905-804b64d4-3de2-11e8-9f91-04b821c4730b.gif)

### Additional information
I think I figured out how to get this working by simply adding a new snippet where the prefix includes the `\`. For example for the `\section` command, adding the snippet below **before** the entry for section in `language-latex.cson` works for me (would be nice if someone could verify this):
```cson
  '\\section':
    'prefix': '\\section'
    'body': '\\\\section{${1:section name}}\n$0'
```

**Comment by ericcornelissen** [comment]
First of all, my apologies for not finding the other issues related to this topic 😅 

Secondly, if the reason you pointed out were true I understand that you won't fix it. However, I created the example .gifs using the snippet I provided (not sure why it works), would you at least be willing to try that and see if it works? (I only tried it on Windows so far, Atom v1.25.1)

**Comment by Aerijo** [comment]
Yep, I just tried it and it seems to work (1.26.0-beta1). I'll remove the `wontfix` label then, and support any PR to change it.
