### ISSUE TITLE
Add shortcut to add next line in environments

### ISSUE THREAD

**Issue by deiga** [area/language-latex#19]
As an example I'd love to press `ctrl+enter` or something similar to make a new line and start it with the appropriate markup.
 For example `\item` in and `itemize` block

**Comment by flapperleenie** [comment]
+1

**Comment by Gwnl** [comment]
+1

**Comment by yudai-nkt** [comment]
I don't think this feature should be offered by this package, which only provides syntax highlighting and some fundamental snippets.

**Comment by deiga** [comment]
I think you're right, it would be better suited in https://github.com/msiniscalchi/atom-latextools
