### ISSUE TITLE
\lstinline|$ENV_VARIABLE|

### ISSUE THREAD

**Issue by redfast00** [area/language-latex#190]
### Prerequisites
- [X] Put an `X` in this box if you have done the following:
  - Ensured the issue has not already been raised
  - Ensured the issue is caused by this package

### Description

It incorrectly highlights the rest of the code as math (?) environment

```
This is a test: \lstinline|$ENV| and this was my environment variable

Test
```

#### Expected behaviour
Normal colors

#### Actual behaviour
Everything is yellow (probably because of the $)

**Comment by Aerijo** [comment]
@redfast00 I've pushed a commit to fix that issue. It will most likely come out in the next release, but I don't have an ETA on that. You can get this change and all unreleased changes by 
- cloning this repo, 
- possibly needing to delete the existing `language-latex` folder in `~/.atom/packages`
- running `apm link` inside the clone's root level on the command line
- restart Atom
