### ISSUE TITLE
No backslash in snippet expansion

### ISSUE THREAD

**Issue by JohannWeging** [area/language-latex#30]
When I trigger a snippet for example `sec` I get
```latex
section{section name}
label{sec:section label}
```
To make it work again I modified the snippet to:
```cson
'Section':
    'prefix': 'sec'
    'body': '\\\\section{${1:section name}}\n\\\\label{sec:${1:section label}}\n$2'
```
Can someone confirm this?

Atom Version: 0.190.0
OS: Linux

**Comment by Gwnl** [comment]
Same here with OSX 10.10.3. This problem seems to be present for all the snippets in this package. Has something changed in the way snippets are defined within Atom?

**Comment by thomasjo** [comment]
I've fixed the problem in https://github.com/area/language-latex/pull/32. Caused upstream by a breaking change in https://github.com/atom/snippets/pull/123.
