### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by davidneat** [area/language-latex#33]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app/src/package.js:550:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/package.js:172:43)
```

i'm not sure if this issue is still relevant as i was on an older version of atom.

**Comment by area** [comment]
Fixed via #24
