### ISSUE TITLE
\emph{} not recognized

### ISSUE THREAD

**Issue by stockphrase** [area/language-latex#34]
I'm using your package but it is not highlighting the \emph tag or the /textbf{} tag.

**Comment by flapperleenie** [comment]
There are other shortcuts (used in Sublime Text 2) that would help immensely... I'm thinking of 
* 'cmd + enter' for inserting *\item* in a new line
* $ becoming $><$ automatically
* 'cmd + L + C' = >\cmd<{}
Is there an easy way to change the settings in keybindings? I also haven't been able to change the default `` to `'...

**Comment by MatteoRagni** [comment]
Also, it could be nice (but I dunno if possibile) to render in _italic_ `\emph` text (and `\textit`, etc.), while render in **bold** text for `\textbf`... But I believe that it depends on pygmentation scheme (css?), not on language pack. Am I right?

**Comment by area** [comment]
Both now seem to work. If I'm mistaken in what you mean, please let me know.
<img width="108" alt="screen shot 2016-10-02 at 10 47 48" src="https://cloud.githubusercontent.com/assets/311812/19019863/b93c25be-888d-11e6-8a80-e78f5508ccd3.png">
