### ISSUE TITLE
Recognize sections as symbols

### ISSUE THREAD

**Issue by mdlincoln** [area/language-latex#35]
It would be a great feature to recognize `\section{}`, `\subsection{}` and the like as symbols that can be navigated to using Symbols View.

**Comment by fabianp** [comment]
+1. I've been missing this too

**Comment by cedhuf** [comment]
Hello,
As far as i can see it's working out of the box. `cmd + r` give me a list of all section and subsection. However there is a nasty bug, the line presented by symbols view are not the good one. Please confirm that i have a good understanding of your request and that this is working on your side.

Thanks.

**Comment by area** [comment]
I think the fact that this works at all is more by luck than judgment, currently. I have a PR in at https://github.com/atom/symbols-view/pull/195 that will make this work correctly.

**Comment by area** [comment]
My PR has been merged into `symbols-view`, so this should now work as intended.
