### ISSUE TITLE
Incorrect snippets

### ISSUE THREAD

**Issue by ReggioG** [area/language-latex#37]
There is several snippets for which the prefix does not match the body.
Examples : prec, prod, sup, int, infty, succeq, preceq, succeq...

**Comment by B1ackCa7** [comment]
Those are for toggling between them.

It seems that the problem is that they should have different names even with the same body, and the latter ones seem to overwrite the former ones.

**Comment by yudai-nkt** [comment]
Those snippets are no longer available
