### ISSUE TITLE
Display Math prefix not recognized

### ISSUE THREAD

**Issue by hzach** [area/language-latex#39]
Typing the '$$' prefix does not trigger the Display Math snippet. My guess is that '$' is a special character in LaTeX and therefore cannot be used as a snippet prefix?

**Comment by cedhuf** [comment]
Hi,
Thanks for your commit and participation ! The $$ is working fine here (the same way your commit does), opening :
> \\[
>  (cursor here)
> \\]

Which is, i guess (not used to math in latex), the correct behavior. Can you please check on that (you may have some bug coming from other plugins or atom) ? However i'm ok with the fact that we may have to change the name of the snippet with something more distinct than $$.

For the second part of your commit, referring to [that] (http://tex.stackexchange.com/questions/40492/what-are-the-differences-between-align-equation-and-displaymath) :
>However, using the $$ method to initiate and terminate display-math mode in LaTeX documents is nowadays heavily deprecated.

So i don't see the need for this 'math' addition. I'm waiting for more opinion and advice on that.
Have a nice day,

**Comment by hzach** [comment]
@cedhuf Thanks for you feedback. I now admit I was wrong about the bug; I guess it was because typing `$$` didn't trigger the snippet drop down in the editor. I was a bit trigger happy with that, so I humbly apologize. However definitely agree that about the naming issue. The fact that `$$` triggers `\[...\]` seems a bit contradictory. So even though the proposed change is somewhat spawned from false pretenses, I think its still worth considering.
Lastly, note that the `math` snippet addition actually triggers in-line math mode, e.g. `$...inline_math_here...$`, and not display-math mode, e.g. `$$ ...display_math_here...$$`. But actually what might be really nice is if `$` auto-closed when typed in the same way `[`, `{`, `(`, etc. I can look into that.

**Comment by cedhuf** [comment]
> Lastly, note that the math snippet addition actually triggers in-line math mode, e.g. $...inline_math_here...$, and not display-math mode, e.g. $$ ...display_math_here...$$.

Oh yes ! My bad. I'm not used to math in latex so i might say some incredibly stupid thinks on this !

> So even though the proposed change is somewhat spawned from false pretenses, I think its still worth considering.

It is. I will merge your pull request, even if i'm not really happy with the prefix used to call those snippets. Maybe we can find something nicer that better represent inline math and classic one (e.g., math and inmath ?).

> But actually what might be really nice is if $ auto-closed when typed in the same way [, {, (, etc. I can look into that.

I think it's more a general Atom behavior and we can't do much about this here.
Br,
