### ISSUE TITLE
Autocompletion fails with backslashes

### ISSUE THREAD

**Issue by aclarembeau** [area/language-latex#42]
Hello every body. Thank you for this great package. 
There's a problem on the new version of Atom (1.0). When I type `\beg` to insert an environnement, such as `\begin{equation}`, the autocompletion always purposes me  `\\begin{` instead of `\begin`. It's the same for everything that starts with a backslash. `\sec` give me `\\section`, et cetera. 

For me, the problem comes from the following file: 
https://github.com/area/language-latex/blob/master/snippets/language-latex.cson

Another strange thing is that when I type `\sec`, it purposes me 
```\\section{section name}
\label{sec:section label}```
The backslashes before label are correct but those before section aren't. 

A quick fix for me is to remove 2 backslashes for the command that gave me problem (I usually just remove the first two backslash, the four last are mandatory. For instance:

The default file value: 
```
  '\\\\begin{}…\\\\end{}':
    'prefix': 'begin'
    'body': '\\begin{${1:env}}\n\t$2\n\\\\end{${1:env}}'
```
Give me: `\\begin{env} ... \end{env}`
```
  '\\begin{}…\\end{}':
    'prefix': 'begin'
    'body': '\\begin{${1:env}}\n\t$2\n\\\\end{${1:env}}'
```
Give me: `\begin{env} ... end{env}`
```
  '\\begin{}…\\\\end{}':
    'prefix': 'begin'
    'body': '\\begin{${1:env}}\n\t$2\n\\\\end{${1:env}}'
```
Give me: `\begin{env} ... \end{env}` = the correct value

Maybe it could be useful to search the deep origin of the problem. 

Thank you :)

Note: I'm on Ubuntu 14.04 (and sorry if I'm not very clear, my English isn't very good :) )

**Comment by cedhuf** [comment]
Hi,
Thanks  for your feedback. When you type `sec +tab` you are using the snippet and it will automatically add 
>\section{section name}
> \label{sec:section label}`

If you start by `\` and then `sec +tab` it will automatically replace `sec` by `\section{section name}` and you will still have this little `\` that as nothing to do here. Your issue probably come from this. Your correction will end up with deleting the `\` for people using only `sec` as a snippet.

Please confirm that everything is working on your side.
Br,
