### ISSUE TITLE
No more commands interpreted after 26/27 in one line

### ISSUE THREAD

**Issue by klicperajo** [area/language-latex#44]
After using commands or brackets (`[a]` or `{a}`, non-empty; empty brackets also count, but somehow differently) in any combination for 27 times in a single line, all further commands will be broken. The text will then be either white or green, depending on the environment you were in before. Examples:

    this is normal \1 \2 \3 \4 \5 \6 \7 \8 \9 \10 \11 \12 \13 \14 \15 \16 \17 \18 \19 \20 \21 \22 \23 \24 \25 \26 \27 this \is $ all \white $here$!

    this is normal \1 \2 \3 \4 \5 {6} \7 \8 [9] \10 \11 \12 \13 \14 \15 \16 \17 \18 \19 \20 \21 \22 \23 \24 \25 \26 {27} this \is $ all \white $here$!

    this is normal \1 {2} [3] \4 \5 \6 \7 \8 \9 \10 \11 \12 \13 \14 \15 \16 \17 \18 \19 \20 \21 \22 \23 \24 \25 \26 $ \27 this \is $ all \green $here$!

if three or more brackets are used, only 26 are usable:

    this is normal {1} {2} [3] \4 \5 \6 \7 \8 \9 \10 \11 \12 \13 \14 \15 \16 \17 \18 \19 \20 \21 \22 \23 \24 \25 \26 $ this \is $ all \white $here$!

Additionally, if there is a comment right before the line where the commands break, the rest of the document will stay in the environment defined before! Example:

    % some comment
    this is normal \1 {2} [3] \4 \5 \6 \7 \8 \9 \10 \11 \12 \13 \14 \15 \16 \17 \18 \19 \20 \21 \22 \23 \24 \25 \26 $ \27 this \is $ all \green $here$!
    in \working math mode! $ now it's \working white text again.

**Comment by cedhuf** [comment]
It's probably due to atom limitation, see https://github.com/area/language-latex/issues/13 for more information.
