### ISSUE TITLE
Snippets don't work in math environment

### ISSUE THREAD

**Issue by Rdbllx** [area/language-latex#47]
Hi, I tried to use snippets in a math environment like this one $$ or \[ \] but it doesn't work.
Is it normal ? 
Thank's in advance for your answers

**Comment by Rdbllx** [comment]
I need some help please, can someone help me or if someone knows how to fix it ?

**Comment by Rdbllx** [comment]
Could someone answer please ?

**Comment by area** [comment]
Dupe of #56 which, while this one came first, has a little more info.
