### ISSUE TITLE
biblatex cite commands not recognized

### ISSUE THREAD

**Issue by NickRSearcy** [area/language-latex#50]
Ideally, `\parencite{turing1950}` would trigger the same highlighting as `\citep{turing1950}` or simply `\cite{turing1950}` but it does not.

I would be happy to try to edit the grammar and submit a pull request but I cannot figure out where the `\citep{}` or the `\cite{}` behavior is coming from.

**Comment by area** [comment]
Fixed in 0890a6ad3bb7f2b5fc8a171a94c379adadcdf321
