### ISSUE TITLE
Wrong Syntax Highlighting in Math Mode

### ISSUE THREAD

**Issue by mholzhauser** [area/language-latex#52]
In many of my TeX-Files, the Plugin does not recognize the end of the math mode in case that there are many inline math blocks within some paragraph.

I was not able to get a minimal working example, but this one is the smallest I could reproduce:

> foo $i \in \\{1,\ldots,k\\}$ bar $x$ foo $i \in \\{1,\ldots,k\\}$ bar $g_i^{(1)}(x) \colonequals \frac{x}{a_i - 1} \cdot \frac{1}{2}$ foo $g_i^{(2)}(x) \colonequals (x - (a_i - 1)) \cdot (a_i - \frac{1}{2}) + \frac{1}{2}$ why is this green?

At least in my case (latest Atom, One Dark Theme) it looks like this:
![bildschirmfoto 2015-09-04 um 13 39 13](https://cloud.githubusercontent.com/assets/14125369/9682892/1ece8386-530b-11e5-9e06-c47a09b6c960.png)

So, as you can see, it does not detect the end of the last math block.

**Comment by Rdbllx** [comment]
Are the snippets working in math blocks for you?

**Comment by Rdbllx** [comment]
*are snippets

**Comment by mholzhauser** [comment]
Yes, when I type 'la' and press TAB, it fills in \langle (e.g.).

It seems to have something to do with the backslashes. I just noticed that in the example I posted above the backslashes for the sets were missing (possibly due to github) and wondered why everything is colored as it should. I corrected the example above.

Yet, I found another example with strange coloring:
> $\kappa$ foo $\kappa\geq 1$ bar $\kappa\geq 1$ foo \ref{lem:CGFP:FlowDistribution} foo $\o{C}$ bar $\o{C}$ foo \ref{fig:CGFP:EdgeJoin_UndirectedCycle}

The last reference is not colored as it should.
![bildschirmfoto 2015-09-07 um 11 49 39](https://cloud.githubusercontent.com/assets/14125369/9714202/8ba66f76-5556-11e5-922d-08ee76902f01.png)

**Comment by Rdbllx** [comment]
Yes me too, but does it work if you put $$ around ? For example, if you type $ la + tab $ does it work ? Or how you do it to around words with $$ and still use snippets ?

**Comment by mholzhauser** [comment]
Yes, that works for me. Inside and outside of math environments.

**Comment by Rdbllx** [comment]
ok, have you done something else than to install this package ? What operating system do you use ?

**Comment by mholzhauser** [comment]
I have also installed the "latex" package and "latexer", but that's it. I'm running on Mac OS X (latest), but I will also try to reproduce it on Windows.

Can anyone else reproduce the error?

**Comment by bstellato** [comment]
Same problem here with the first example colors. I have OSX and latest versions of latex, latexer and language-latex plugins. 

```
\documentclass{standalone}
\usepackage{colonequals}

\begin{document}
foo $i \in \{1,\ldots,k\}$ bar $x$ foo $i \in \{1,\ldots,k\}$ bar $g_i^{(1)}(x) \colonequals \frac{x}{a_i - 1} \cdot \frac{1}{2}$ foo $g_i^{(2)}(x) \colonequals (x - (a_i - 1)) \cdot (a_i - \frac{1}{2}) + \frac{1}{2}$ why is this green?
\end{document}
```

**Comment by bstellato** [comment]
It seems to be an Atom limit of the number of Tokens at the moment: https://github.com/atom/atom/issues/1667

It is possible to install this package https://github.com/postcasio/atom-grammar-token-limit to change the maximum number of tokens allowed.

**Comment by mholzhauser** [comment]
Thanks for the answer, the token limit was the problem indeed. I' closing this issue since the discussion will be held at the Atom page.
