### ISSUE TITLE
Snippets don't work in math display

### ISSUE THREAD

**Issue by Rdbllx** [area/language-latex#56]
Hello everyone, 
First I'd like to thank you for all this work. But I have an issue.
I can't use snippets when I'm in a math display e.g. 
If I write $$, then beetwen these 2 "$" I can't use snippets like for example a + tab ( for \alpha).
If someone knows why or how to fix it, could he please help me ?
Thank's in advance for all your answers

**Comment by Rdbllx** [comment]
If I want to be more precise, I can't see the snippet drop-down menu when I'm writting in math display. Is it normal ?

**Comment by Rdbllx** [comment]
Please can someone answer?

**Comment by Rdbllx** [comment]
If think it could come from the highlighting.

**Comment by Rdbllx** [comment]
It appears to come from the fact that when you write in math mode it is detected as a comment and when you are typing comments, it is normal to think that you don't really need snippets. Can someone update this package please ?

**Comment by Aerijo** [comment]
This is old.

If you still care, it is because the math environment is scoped to quote and quotes are not supported by autocomplete-snippet package.

The solution would be to change that (core) package somehow, or totally revamp how math mode is scoped by this package. Neither option is particularly easy.

**Comment by Aerijo** [comment]
See my response in https://github.com/area/language-latex/issues/120 for a workaround method.

**Comment by yudai-nkt** [comment]
This is an issue about snippet expansion and is different from #120, which is about snippet autocompletion. Do you still see this problem, @Rdbllx?

**Comment by Aerijo** [comment]
@Rdbllx @yudai-nkt I think another issue here is that there is no snippet in this package for `\alpha`. If someone can reproduce this issue with `frac` there would be something wrong, but I can't find the problem. I am not able to test this properly though, as I have modified my versions of the snippet packages already to fix the autocomplete popup menu.

If no one can reproduce this issue, I don't see any value in keeping it open. If some other user runs into it (which I doubt), they will be able to open a new one.

**Comment by yudai-nkt** [comment]
Snippets for Greek alphabets were in the package in 2015, so there should have been a problem for @Rdbllx when this issue was made. However, this issue is silent for quite a long, hence it's safe to close.
