### ISSUE TITLE
Multiple itemize in Latex 

### ISSUE THREAD

**Issue by ThibaudDauce** [area/language-latex#58]
Hi,

I ran into a strange bug today.

If I type in a new `test.tex` file:
```tex
text before
\begin{itemize}
    \item line 1
    \begin{itemize}
        \item line 2 in an other itemize
    \end{itemize}
\end{itemize}
```

And if I try to update the first line, Atom try to put a new `\end{itemize}` after my cursor like this (I put my cursor before `line 1` and type `firs`)
```tex
text before
\begin{itemize}
    \item firs
    \end{itemize}line 1
    \begin{itemize}
        \item line 2 in an other itemize
    \end{itemize}
\end{itemize}
```

If I remove the line `text before`, everything works fine.

I'm using Atom 1.0.19 with Archlinux.

Thanks.

**Comment by area** [comment]
Unable to reproduce with Atom 1.10.2. If you're still having difficulties, please let me know.
