### ISSUE TITLE
Line numbers gone

### ISSUE THREAD

**Issue by aztek56** [area/language-latex#60]
I am using this plugin, and the hightight is great! But when I use it I loose my line numbers. Please help!

![image](https://cloud.githubusercontent.com/assets/2037339/11204759/d97e89b2-8cb6-11e5-9003-ff59732e7675.png)

**Comment by area** [comment]
This certainly isn't happening for me. Are you still encountering the issue with an up-to-date atom and `language-latex`? If so, I'll reopen and investigate some more.
