### ISSUE TITLE
Incorrect treatment of continued quotes through a paragraph break

### ISSUE THREAD

**Issue by makyo** [area/language-latex#61]
When writing prose, if the speaker speaks in multiple paragraphs, style indicates that the trailing quotation mark be dropped between paragraphs:

``` latex

``This is paragraph one

``And then I continued the thought into paragraph two''

This paragraph was not said by anyone. % this paragraph is highlighted
```

The last paragraph should not be highlighted as though it were in quotation marks, but is.  I find myself writing:

``` latex

``This is paragraph one

``And then I continued the thought into paragraph two''XXX''

This paragraph was not said by anyone. % this paragraph is not highlighted.
```

to keep the highlights happy, then deleting it before running `latex` on the file.  It seems as though a newline should cancel quotation highlighting.

**Comment by area** [comment]
I'm thinking about this, but any solution also has to correctly highlight the cases


```
``This is paragraph one
broken over two lines

``And then I continued the thought into paragraph two''
```

```
``This is paragraph one
broken over two lines''

``And someone else continued the thought into paragraph two''
```

So simply stoping quotation highlighting upon a newline isn't the solution.

**Comment by cjm715** [comment]
My latex code is highlighted for the remainder of my document after using the tilde character ` for a starting quote.

**Comment by yudai-nkt** [comment]
I don't understand the situation, but why do you use unbalanced quotation marks?

**Comment by area** [comment]
Taken from [Stack Exchange](https://english.stackexchange.com/questions/96608/why-does-the-multi-paragraph-quotation-rule-exist)

>“That seems like an odd way to use punctuation,” Tom said. “What harm would there be in using quotation marks at the end of every paragraph?”

>“Oh, that’s not all that complicated,” J.R. answered. “If you closed quotes at the end of every paragraph, then you would need to reidentify the speaker with every subsequent paragraph.

>“Say a narrative was describing two or three people engaged in a lengthy conversation. If you closed the quotation marks in the previous paragraph, then a reader wouldn’t be able to easily tell if the previous speaker was extending his point, or if someone else in the room had picked up the conversation. By leaving the previous paragraph’s quote unclosed, the reader knows that the previous speaker is still the one talking.”

>“Oh, that makes sense. Thanks!”

**Comment by yudai-nkt** [comment]
Uh, my comment was a reply to someone who seems to have deleted his/her comment saying that using <code>`</code> collapses the highlight... Anyway thanks for the reference, I didn't know this rule!

**Comment by cortner** [comment]
newline doesn't declare a new paragraph in Latex, but an empty line does.  So why can't you reset highlighting after an empty line?

**Comment by lierdakil** [comment]
FWIW, I don't think there's much benefit to highlighting text inside quotes. LaTeX quotation marks are just shorthands for typographic symbols and IMO should be treated as such. LaTeX itself doesn't treat text between quotes any different than text outside quotes, and unbalanced quotation marks is perfectly valid LaTeX.

**Comment by yudai-nkt** [comment]
Currently ``` ``...'' ``` is scoped to `string.quoted.double.latex` (and single counterpart to `single`). It is somewhat different from what "quotation" means in other languages. E.g., `cat filename containing space` in shell script tries to look for three files `filename`, `containing` and `space`. In such case we write `cat 'filename containing space'`, and this is similar to what `{}` does in TeX assuming normal catcodes.

``` `` ``` and ``''`` have a special meaning as they get ligatured from ASCII characters to actual punctuations. The content string doesn't have any significant meaning for TeX and remains as it is. Therefore I totally agree with @lierdakil, but abolishing highlighting the content, which I'm personally in favor of, is a bit subjective I think.

**Comment by area** [comment]
> unbalanced quotation marks is perfectly valid LaTeX.

Seeing this put so starkly definitely pulls me in the direction of abandoning highlighting quoted text altogether.

**Comment by lierdakil** [comment]
Here's one other case where this also fails miserably -- at least for single quotes that is:

```latex
`I say, you didn't taste Britain unless you tasted fish'n'chips, mate,' said John
```

Here, existing rules in language-latex incorrectly assume that quote is closed upon first `'`.

I believe british english has a preference for single quotes, and existing typesetting practice prefers curly apostrophe (i.e. right single quote):  **’**
to straight one:  **'**
everywhere except the beginning of a word, e.g.
> **'Twas** a week before Halloween

vs
> **Margaret’s** dress

Note that differentiation between closing quote and apostrophe is not possible in general due to existence of possessive plural forms (at least without semantic context that is):

> **Users’** feedback wasn’t very favorable

Also nouns ending with -s/x/c/z(e) are often written without ‘s’ in possessive form:

> **convenience’** sake, **goodness’** sake, etc

although different style manuals suggest different rules for this case.

**Comment by yudai-nkt** [comment]
I've just made a PR that abolishes grammars about quotation marks. Punctuations that will be ligatured by the Babel package will be abolished for same reason.

**Comment by chipotle** [comment]
Is it possible for someone to merge the PR that @yudai-nkt referenced above? I just came across this bug myself. (Because one paragraph in dialogue doesn't end with the `''` mark, the last quarter of my novel is highlighted as if it's one huge quote!)
