### ISSUE TITLE
\begin{} / \end{} highlighting broken with long identifiers (> 8 characters)

### ISSUE THREAD

**Issue by l0calh05t** [area/language-latex#63]
While using the listings package, I noticed that \begin{lstlisting} ... \end{lstlisting} is not highlighted correctly. Shorter identifiers (8 characters or less), such as the shorter but incorrect \begin{lstlistin} ... \end{lstlistin} are highlighted properly.

**Comment by area** [comment]
Same as #71, so should be fixed in latest release.
