### ISSUE TITLE
\begin{itemize} \end{itemize} autocomplete broken

### ISSUE THREAD

**Issue by drpotato** [area/language-latex#65]
The issue arose when trying to create an itemized list. When trying to add an item before Item 1, `\end{itemize} is automatically added underneath Item 1.

```latex
\begin{itemize}
	\item Item 1
	\begin{itemize}
		\item Item A
		\item Item B
		\item Item C
		\item Item D
	\end{itemize}
	\item Item 2
	\item Item 3
	\item Item 4
\end{itemize}
```

I'm going to attempt to fix it myself.

**Comment by Evpok** [comment]
I had that issue. It was caused by the `latexer`  package. Try to disable
it if it is installed. If you want environment autoclosing still, I have
written https://atom.io/packages/latex-autocomplete

**Comment by drpotato** [comment]
Well damn, guess I'll just close this. I'd uninstalled `latexer` it because I though it was causing problems but failed to restart Atom.
