### ISSUE TITLE
Minor: highlighting of lstlisting environment

### ISSUE THREAD

**Issue by mikaelec** [area/language-latex#71]
I have a strange problem, the highlighting of the begin in a lstlisting environment doesn't work, but only for lstlisting environments.

E.g. the following will not highlight the 'begin' word.
```latex
\begin{lstlisting}
...
\end{lstlisting}
```

However, the following highlights the 'begin' word as expected (intentionally misspelt the lstlisting words in the begin command):
```latex
\begin{lstlistin}
...
\end{lstlisting}
```

```latex
\begin{lstlistingg}
...
\end{lstlisting}
```

**Comment by nykh** [comment]
Same issue here. From the activity it looks like the author fixed this specific problem 8 months ago

>  Fix simple \begin{lstlisting} syntax highlighting 

However for some reason this update is not propagated to apm hosting. I wonder what's stopping him from doing a new release. Last release was last year.

**Comment by area** [comment]
A new release has been made, including this bugfix.
