### ISSUE TITLE
:art: Clean the regex up

### ISSUE THREAD

**Issue by Evpok** [area/language-latex#74]
Some patterns (eg entity.name.section.latex) seem to have carried away some cruft from the TextMate bundle, such as irrelevant tabulators or comments. I am not well versed enough in Atom grammars to know if this is
  - useful
  - useless, but harmless
  - harmful

Should those regex be cleaned up? If so, I can probably do it, if not, could it be stated somewhere why? As is, it is a bit confusing.

**Comment by area** [comment]
Yeah, these definitely need to get cleaned up. I'm honestly surprised no-one complained about this before! I propose:

* Replace \n with actual newlines
* Replace \t with actual tabs
* Triple quote the resulting string

By doing this rather than simply deleting the \n and \t, we get to keep the comments, and split our regexs over multiple lines, making them easier to update in the future. So, for example:

```    
'begin': '(?x)\n\t\t\t\t\t(\n\t\t\t\t\t\t(\\\\)\t\t\t\t\t\t\t\t\t\t# Marker\n\t\t\t\t\t\t(?:auto)?(?:foot)?(?:full)?(?:no)?(?:short)?\t\t# Function Name\n\t\t\t\t\t\t[cC]ite\n\t\t\t\t\t\t(?:al)?(?:t|p|author|year(?:par)?|title)?[ANP]*\n\t\t\t\t\t\t\\*?\t\t\t\t\t\t\t\t\t\t\t# Optional Unabreviated\n\t\t\t\t\t)\n\t\t\t\t\t(?:(\\[)[^\\]]*(\\]))?\t\t\t\t\t\t\t\t# Optional\n\t\t\t\t\t(?:(\\[)[^\\]]*(\\]))?\t\t\t\t\t\t\t\t#   Arguments\n\t\t\t\t\t(\\{)\t\t\t\t\t\t\t\t\t\t\t# Opening Bracket\n\t\t\t\t'
```

Becomes

```
'begin': '''(?x)
		(
			(\\\\)										# Marker
			(?:text)?(?:paren)?(?:auto)?(?:foot)?(?:full)?(?:no)?(?:short)?		# Function Name
			[cC]ites?
			(?:al)?(?:t|p|author|year(?:par)?|title)?[ANP]*
			\\*?											# Optional Unabreviated
		)
		(?:(\\[)[^\\]]*(\\]))?								# Optional
		(?:(\\[)[^\\]]*(\\]))?								#   Arguments
		(\\{)											# Opening Bracket
	'''
```

Note that the whitespace is ignored when doing the actual regex, due to the (?x) at the start.

**Comment by yudai-nkt** [comment]
I actually did this clean-up in yudai-nkt/language-tex@8a0c8a2ae0045d42ccecf6a890a6947f18a74645. It wasn't done in `master` branch, but is quite stable for me. I will apply this patch when I set up the repository on my local end.

**Comment by area** [comment]
Do you not see value in the multi-line approach, and keeping the comments in the regex expressions?

**Comment by yudai-nkt** [comment]
It may enhance the visibility, but for instance If we rewrite [this line](https://github.com/area/language-latex/blob/master/grammars/latex.cson#L1477) like your suggestion (I used spaces as mixing tabs and spaces is usually thought to be a bad habit), it turns into

```coffeescript
    'end': '''(?x)
           (?:\\s*) # Optional whitespace
           ((\\\\)end) # Marker - Function
           (\\{) # Open Bracket
           (\\4) # Previous capture from begin
           (\\}) # Close Bracket
           (?:\\s*
           )? # Match to end of line absent of content
           '''
```

There are eleven spaces at the beginning of line 2 to 8, which is incompatible with two-space indent.

If we write like this,

```coffeescript
    'end': '''(?x)
              (?:\\s*) # Optional whitespace
              ((\\\\)end) # Marker - Function
              (\\{) # Open Bracket
              (\\4) # Previous capture from begin
              (\\}) # Close Bracket
              (?:\\s*
              )? # Match to end of line absent of content
           '''
```

There are fourteen spaces, but the number of spaces before the closing `'''` is still eleven. Same thing can be said for `begin` entries.

There are some other reasons against multi-line approach, but this is the most notable one.

**Comment by area** [comment]
I definitely think that having an awkward alignment is worth the gain of having the regexes easier to understand.

**Comment by yudai-nkt** [comment]
Okay, I'd follow that way then. Are there any standards or distinction about what to use multi-line approach and what to use one-line approach?

**Comment by area** [comment]
I think the regex's that are multi-line originally came from the textmate bundle, and those that aren't have been put in afterwards.

If the regex is simple, it's fine to have it as one line. Unfortunately, there's obviously no hard-and-fast rule for what simple is! We'll just have to use our judgment.

**Comment by yudai-nkt** [comment]
When I convert

```coffeescript
   'begin': '(?x)\n\t\t\t\t(\t\t\t\t\t\t\t\t\t\t\t\t\t# Capture 1\n\t\t\t\t\t(\\\\)\t\t\t\t\t\t\t\t\t\t\t# Marker\n\t\t\t\t\t(\n\t\t\t\t\t\t(?:sub){0,2}section\t\t\t\t\t\t\t# Functions\n\t\t\t\t\t  | (?:sub)?paragraph\n\t\t\t\t\t  | chapter|part|addpart\n\t\t\t\t\t  | addchap|addsec|minisec\n\t\t\t\t\t)\n\t\t\t\t\t)(?:\\*)?\t\t\t\t\t\t\t\t\t\t\t# Optional Unnumbered\n\t\t\t\t\n\t\t\t\t(?:\n\t\t\t\t\t(\\[)([^\\[]*?)(\\])\t\t\t\t\t\t\t\t# Optional Title\n\t\t\t\t)??\n\t\t\t\t(\\{)\t\t\t\t\t\t\t\t\t\t\t\t# Opening Bracket\n\t\t\t\t'
```

this turns into

```coffeescript
    'begin': '''(?x)
                ( # Capture 1
                (\\\\) # Marker
                (
                (?:sub){0,2}section # Functions
                | (?:sub)?paragraph
                | chapter|part|addpart
                | addchap|addsec|minisec
                )
                )(?:\\*)? # Optional Unnumbered

                (?:
                (\\[)([^\\[]*?)(\\]) # Optional Title
                )??
                (\\{) # Opening Bracket
             '''
```

This splitting is excessively verbose. Something like

```coffeescript
    'begin': '''(?x)
                (\\\\)((?:sub){0,2}section|(?:sub)?paragraph|chapter|part|addpart|addchap|addsec|minisec)(?:\\*)?
                (?:(\\[)([^\\[]*?)(\\]))?
                (\\{)
             '''
```

is composed of three parts (control sequences' name, optional argument, and opening brace) and this is already quite readable for me. So, I don't think we do need to replace `\n` or `\t` one by one.

**Comment by yudai-nkt** [comment]
Any thoughts on this, @area?

**Comment by area** [comment]
Sorry, I could have sworn I replied to this. Yeah, that's fine. We don't need to copy their exact line breaks from the textmate package, I just think splitting the regexes up even a bit helps a lot.
