### ISSUE TITLE
texttt, textbf, emph shortcuts?

### ISSUE THREAD

**Issue by nickeubank** [area/language-latex#76]
Does language-latex have anything to facilitate easily making text bold or italics? Both sublime and textmate have keyboard shorts where one can either (a) highlight text and hit the keys to get it wrapped, or (b) will add a wrapper and leave the cursor in the appropriate place for typing. 

For example, if I type Cmd+b in textmate, I get `\textbf{}` with the cursor inside the squiggly brackets. Similarly, if the word `test` were highlighted and I hit Cmd+b, it would becomes `\textbf{test}`. 

Related: https://discuss.atom.io/t/keybinding-for-italic-bold-text-in-latex/25701

If we don't have it, any chance it could be added? Happy to help, but new to Atom and would probably need some hand-holding. :)

**Comment by area** [comment]
I agree that this isn't quite the right fit for this package, which should be focussed on highlighting and basic snippets.
