### ISSUE TITLE
Multiple \ref's in one line, different colors

### ISSUE THREAD

**Issue by GhostGambler** [area/language-latex#78]
I have a normal text line consisting of text with multiple (5) ref tags "bla bla bla Section~\ref{XYZ} bla bla bla Section~\ref{ZASJKH} …". The coloring of the first three ref tags is correct ("ref" blue, the label green). For the fourth ref tag only the tag is blue, the label is white. The fifth tag is completely white.

**Comment by GhostGambler** [comment]
Addition: It is not a problem of the ref tag. I added a \todo somewhere at the end and it is also not colored. Seems coloring just stops somewhere in the line.

**Comment by GhostGambler** [comment]
This is an example with broken coloring:
```
Lorem Ipsum Section~\ref{sec:Statement of the Problem} Lorem Ipsum Section~\ref{sec:Review of Literature} Lorem Ipsum Section~\ref{sec:Aims / Research Questions} Lorem Ipsum Section~\ref{sec:Methodology} Lorem Ipsum Section~\ref{sec:Plan of Work}
```

**Comment by yudai-nkt** [comment]
This isn't a bug of this package It's an Atom's bug and please refer to atom/atom#1667.
