### ISSUE TITLE
File symbol finder always resolves to line-number - 1

### ISSUE THREAD

**Issue by GhostGambler** [area/language-latex#83]
The file symbol finder (`⌘R`) always lists the wrong line for symbols, exactly one line before the line the symbol is on (ignoring empty lines and lines consisting only of comments).

This can even lead to situations where the symbol is not visible on the screen after searching it and hitting `Enter`, when there are like 100 empty lines in between the line with the symbol and and previous non-empty line.

**Comment by area** [comment]
Upon investigation, I think it's more luck than judgment than this works at all, and I don't *think* it's the responsibility of this package to fix this. I've made a PR at https://github.com/atom/symbols-view/pull/195 that makes this functionality work as intended.

If there's a way for me to achieve this functionality within this package, I'd be all ears.

**Comment by area** [comment]
My PR has been merged into `symbols-view`, so this should now work as intended.
