### ISSUE TITLE
New lines start highlighted if previous line preceded by comment

### ISSUE THREAD

**Issue by p2j** [area/language-latex#88]
First, I really love this package. It's made writing my research papers a lot more enjoyable. However, I've experienced two bugs with syntax highlighting.

1.  [Red circle] After a long line of characters (in this example it's after 1407 characters, but in attempts to reproduce, the number of characters varies) syntax highlighting stops. In my example, it's in the middle of a citation, and no syntax is highlighted through the end of the line.
2. [Red arrows] If a paragraph is preceded by a comment line like in line 1 of the example attached, following new lines have strange highlighting through the first 100 characters. This goes away if an empty line is put between the comment and the first line of text.

These bugs don't make the product unusable. They are simply cosmetic. But, it is unexpected behavior that I don't know how to fix... 

<img width="931" alt="screen shot 2016-10-06 at 9 24 32 pm" src="https://cloud.githubusercontent.com/assets/4281855/19176279/2a087bfe-8c0c-11e6-9502-10ae4ae6d727.png">

**Comment by yudai-nkt** [comment]
Regarding the first problem, this package is not to blame. It's an Atom's limitation (please refer to atom/atom#1667). I will investigate the second one later, and it would be very appreciated if you post the example code in text so that I can easily reproduce.

**Comment by p2j** [comment]
I was unaware of the Atom limitation, thanks for pointing it out. Here's the example text:

% test comment
Lorem ipsum \emph{dolor sit amet}, consectetur adipiscing elit. Sed sem libero, lacinia at dolor in, dignissim laoreet ligula. Duis pretium imperdiet nisi, in rutrum eros consequat id. Fusce cursus tincidunt ipsum, ac auctor leo dignissim sed. Morbi eget erat a nisl tempus convallis nec quis risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc mattis \( malesuada enim. Sed rutrum congue\) rhoncus. Nam mollis eget eros in luctus. Vestibulum diam quam, molestie at metus ut, rutrum commodo risus. ``Ut eleifend feugiat posuere. Aliquam vel vestibulum ipsum. \emph{Mauris quis maximus} elit. Aliquam eu justo lorem. Phasellus venenatis nibh ut justo sodales, vitae tempor velit ultrices. Aliquam id orci eget diam mollis euismod'' \cite{Aliquam}. convallis ipsum id rhoncus tincidunt. Donec consequat tellus in urna mattis, vel auctor leo malesuada. Morbi nibh mi, ultrices ut mauris eu, sodales bibendum eros. Duis egestas vehicula odio, id dictum neque consequat nec. Praesent ultricies arcu quis diam mollis, \emph{bibendum fermentum} sem semper. Ut in fringilla lacus. In hac \cite{habitasse} \cite{platea} \cite{dictumst}. Mauris eget orci lacu's. Maecenas sit amet magna ullamcorper, porta neque id, sagittis nisl. Proin tristique bibendum volutpat. Sed nisi libero, pretium quis est ac, elementum maximus nibh. Sed laoreet, velit ac feugiat efficitur, \cite{eros-dui-vulputate risus}, sollicitudin elementum mi felis tristique eros. \emph{Praesent} \cite{pharetra} \cite{viverra} elit, eget sodales leo fringilla at. Quisque hendrerit tellus ipsum, nec luctus eros imperdiet \cite{id}.

Vestibulum id ante nulla. Duis euismod condimentum sem. Pellentesque ac auctor lectus. Nullam eu vulputate eros. Nunc neque elit, faucibus ac dui non, tempus sagittis tortor.

Ut rutrum interdum tellus sed suscipit. Sed auctor cursus tristique. Ut volutpat ex augue, ac tincidunt est faucibus ut. Duis at pretium sem. Duis consequat euismod faucibus. Aenean vulputate bibendum orci, sit amet tempor tortor sodales quis. Integer molestie metus sed elit luctus, et hendrerit sapien volutpat. Maecenas interdum odio id lacinia rutrum. Praesent id feugiat lacus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur id imperdiet mauris. Maecenas in nulla quis leo blandit sodales sit amet ut dolor. Pellentesque bibendum posuere orci, quis ullamcorper est venenatis nec. Pellentesque in sem rhoncus, auctor ligula vitae, sollicitudin nunc. Etiam malesuada lorem placerat rhoncus tincidunt. Sed fringilla est ultrices, auctor enim et, viverra elit. Duis et velit ut erat posuere lobortis sed non lacus. Ut ultrices dui tristique lorem fermentum commodo. Proin at dignissim sapien, non malesuada sapien. Maecenas facilisis urna risus, at porta metus dictum mattis. Donec vulputate diam ac nisl rhoncus sodales eget ut nunc. Fusce scelerisque facilisis lectus eu lacinia. Donec dictum, augue vitae ullamcorper varius, nisi metus fermentum lacus, id aliquam ligula ligula at ex. Integer et faucibus risus. Etiam tincidunt, sem eu aliquam molestie, ligula sem venenatis mauris, ultrices consequat ipsum libero vel nisl. Aenean pretium arcu nec ex accumsan vulputate. Vivamus faucibus sit amet felis in sagittis. Maecenas diam dui, lobortis eget tristique ac, bibendum ac ipsum. Duis egestas eros nec tortor volutpat, non tristique nisl pretium. Donec in nisl malesuada, aliquam nibh ut, blandit.

**Comment by yudai-nkt** [comment]
I tested with your code and could reproduce the problem. I do not exactly understand the cause of problem, but I guess this is also somewhat related to Atom's limitation because just breaking lines solves the problem.

```latex
% test comment
Lorem ipsum \emph{dolor sit amet}, consectetur adipiscing elit. Sed sem libero, lacinia at dolor
in, dignissim laoreet ligula. Duis pretium imperdiet nisi, in rutrum eros consequat id.
Fusce cursus tincidunt ipsum, ac auctor leo dignissim sed.
Morbi eget erat a nisl tempus convallis nec quis risus.
Interdum et malesuada fames ac ante ipsum primis in faucibus.
Nunc mattis \( malesuada enim. Sed rutrum congue\) rhoncus.
Nam mollis eget eros in luctus. Vestibulum diam quam, molestie at metus ut, rutrum commodo risus.
``Ut eleifend feugiat posuere. Aliquam vel vestibulum ipsum.
\emph{Mauris quis maximus} elit. Aliquam eu justo lorem. Phasellus venenatis nibh ut justo sodales,
vitae tempor velit ultrices. Aliquam id orci eget diam mollis euismod'' \cite{Aliquam}.
convallis ipsum id rhoncus tincidunt. Donec consequat tellus in urna mattis, vel auctor leo malesuada.
Morbi nibh mi, ultrices ut mauris eu, sodales bibendum eros.
Duis egestas vehicula odio, id dictum neque consequat nec.
Praesent ultricies arcu quis diam mollis, \emph{bibendum fermentum} sem semper.
Ut in fringilla lacus. In hac \cite{habitasse} \cite{platea} \cite{dictumst}.Mauris eget orci 
lacu's. Maecenas sit amet magna ullamcorper, porta neque id, sagittis nisl.
Proin tristique bibendum volutpat.
Sed nisi libero, pretium quis est ac, elementum maximus nibh. Sed laoreet, velit ac feugiat
efficitur, \cite{eros-dui-vulputate risus}, sollicitudin elementum mi felis tristique eros.
\emph{Praesent} \cite{pharetra} \cite{viverra} elit, eget sodales leo fringilla at.
Quisque hendrerit tellus ipsum, nec luctus eros imperdiet \cite{id}.

Vestibulum id ante nulla. Duis euismod condimentum sem.
Pellentesque ac auctor lectus. Nullam eu vulputate eros.
Nunc neque elit, faucibus ac dui non, tempus sagittis tortor.

Ut rutrum interdum tellus sed suscipit. Sed auctor cursus tristique.
Ut volutpat ex augue, ac tincidunt est faucibus ut. Duis at pretium sem. Duis consequat euismod faucibus.
Aenean vulputate bibendum orci, sit amet tempor tortor sodales quis.
Integer molestie metus sed elit luctus, et hendrerit sapien volutpat. Maecenas interdum odio id lacinia rutrum.
Praesent id feugiat lacus.
```
looks like

![2016-10-19 1 04 48](https://cloud.githubusercontent.com/assets/13291527/19486062/13bb050c-9598-11e6-88c9-fc86f1515e03.png)


Would you wrap the text at proper length? I believe more than 1,000 characters in one line is too too much.

**Comment by p2j** [comment]
I made this issue because I thought it was directly related to this package's syntax highlighting. It seems that, instead, my issues stem from Atom limitations. 

Thank you, @yudai-nkt, for your investigation. I will continue to use the kludges to fix the highlighting issues and await for the underlying problems with Atom to be resolved. 

Thus, I don't think this issue is relevant anymore, and so I'm marking it closed.
