### ISSUE TITLE
Requesting 2 snippets

### ISSUE THREAD

**Issue by qazip** [area/language-latex#89]
It would be good if this package had snippets for both the `\cite` and the `\ref` command.

**Comment by yudai-nkt** [comment]
I think it's quite easy to type those short commands. You can also add snippets in your `~/.atom/snippets.cson`:

```coffee
".text.tex.latex":
  citation:
    prefix: "cite"
    body: "\\\\cite{$1}$0"
  reference:
    prefix: "ref"
    body: "\\\\ref{$1}$0"
```

**Comment by mimf** [comment]
I'm aware that one can add the snippet easily (though thank you for the code, that would have taken me a bit of time). I also agree that it's quite easy to type since it's a short command, as you said, but why not add it? I don't think there's anything to lose.

**Comment by yudai-nkt** [comment]
As I stated [here](https://github.com/area/language-latex/issues/84#issuecomment-250756385), I don't like adding snippets. One reason is that it's possible to add in your local setting like the comment above. The other reason, subjectivity, means that different people value different snippets. If we add every snippet that one user wants, `snippets.cson` of this package will be a mess.

That being said, this is merely a collaborator's opinion after all. So, it's worth a discussion or asking @area for opinion.
