### ISSUE TITLE
.beamer snippets not available in .tex

### ISSUE THREAD

**Issue by mimf** [area/language-latex#90]
The `frame` and `columns` snippets are not available in .tex files. They work fine in .beamer though.

```
# Beamer
'.text.tex.latex.beamer':
  'Frame':
    'prefix': 'frame'
    'body': '\\\\begin{frame}[t]{${1:title}}\n\t${2:body}\n\\\\end{frame}\n%--- Next Frame ---%'
  'Columns':
    'prefix': 'cols'
    'body': '\\\\begin{columns}\n\\\\begin{column}[T]{$1cm}\n$3\n\\\\end{column}\n\\\\hfill\n\\\\begin{column}[T]{$2cm}\n\n\\\\end{column}\n\\\\end{columns}\n'


```

**Comment by yudai-nkt** [comment]
It works on my end. Would you make sure that your Beamer file is scoped to `text.tex.latex.beamer`, not just `text.tex.latex`?

**Comment by mimf** [comment]
I don't have a beamer file. I've a .tex file and the frame/column snippets are not working there. 

How do I go about finding out what you asked?

**Comment by yudai-nkt** [comment]
Yes, it should have a `.tex` extension. In short, please check the right side of the status bar. "LaTeX Beamer" should show up.

![2016-10-17 1 24 47](https://cloud.githubusercontent.com/assets/13291527/19418912/b9a32846-9408-11e6-897d-71882580d8da.png)

**Comment by mimf** [comment]
I don't see LaTeX beamer, I only see LaTeX:

**Comment by mimf** [comment]
Sorry, closed by mistake. 

I don't see LaTeX Beamer, all I see is LaTeX.

**Comment by yudai-nkt** [comment]
Then, click the "LaTeX" and change it to "LaTeX Beamer". Snippets will work.

**Comment by yudai-nkt** [comment]
:+1: reaction looks like your problem has been settled, @mimf. Can I close this issue?

**Comment by mimf** [comment]
Yes, thank you.

**Comment by ndaman** [comment]
Follow-up question: I looked in the source and it looks like we try to automatically identify the scope by searching the first line for a documentclass{beamer} statement, but this has not been working for me. Is there a way I can try and debug the scope detection? It would be nice if I didn't need to manually change the scope every time.
