### ISSUE TITLE
Request changing figure snippet

### ISSUE THREAD

**Issue by qazip** [area/language-latex#92]
The current snippet for a figure is

```
\begin{figure}
  \includegraphics{/path/to/figure}
  \caption{}
  \label{}
\end{figure}
```

I find that I pretty much always have to use something like:

```
\begin{figure}
  \includegraphics[with=1\linewidth]{/path/to/figure}
  \caption{}
  \label{}
\end{figure}
```

or instead of **[with=1\linewidth]** something like "[scale=1]".

So my suggestion is to change the figure snippet and add that figure size parameter.

**Comment by yudai-nkt** [comment]
Let me keep the answer on hold until we decide how to cope with adding snippets .

Just for your information: Try typing <kbd>Tab</kbd> after specifying the figure name or path, and the cursor will move to between `\includegraphics` and `{`.

**Comment by Aerijo** [comment]
@qazip Maybe not what you were looking for, but the LaTeX command 
`\setkeys{Gin}{width=\textwidth}` 
will set the default scaling for all images. If you are using the same scale all the time like you say, this could be a better solution.
