### ISSUE TITLE
Support highlighting in markdown file and its preview?

### ISSUE THREAD

**Issue by Edenharder** [area/language-latex#98]
What I want to do is: the latex code will be highlighted when I insert it in the markdown file. 

For example, if the language python is enabled, then python code will be highlighted as following.
![image](https://cloud.githubusercontent.com/assets/6672134/19759048/60b96d8c-9c2b-11e6-8d44-c2220b2104bb.png)

The left one is in the markdown file while the right one is in the preview.

**Comment by yudai-nkt** [comment]
Your feature request should be addressed in the [`language-gfm`](https://atom.io/packages/language-gfm) package, although I'm not sure if they will support every language especially given that this package is not provided by the Atom team.

Please let me know if I misunderstand your point.

**Comment by Edenharder** [comment]
I also installed other language package which is not provided by the Atom team. But they can be highlighted in the markdown preview, although not in the markdown file. For example, [language-mathematica](https://atom.io/packages/language-mathematica)

**Comment by yudai-nkt** [comment]
The `language-*` packages have nothing to do with Markdown preview, and the [`markdown-preview`](https://atom.io/packages/markdown-preview) (including its forks) and your custom stylesheet have the responsibility for rendering Markdown.

> although not in the markdown file.

That makes sense because `language-gfm` doesn't seem to support embedded Mathematica.

**Comment by yudai-nkt** [comment]
You might be interested in atom/language-gfm#175.
